from django.conf.urls import url
from . import views

app_name = 'entities'

urlpatterns = [
    url(
        r'^person/$',
        views.PersonListView.as_view(),
        name='person_browse'
    ),
    url(
        r'^person/detail/(?P<pk>[0-9]+)$',
        views.PersonDetailView.as_view(),
        name='person_detail'
    ),
    url(
        r'^person/create/$',
        views.PersonCreate.as_view(),
        name='person_create'
    ),
    url(
        r'^person/edit/(?P<pk>[0-9]+)$',
        views.PersonUpdate.as_view(),
        name='person_edit'
    ),
    url(
        r'^person/delete/(?P<pk>[0-9]+)$',
        views.PersonDelete.as_view(),
        name='person_delete'),
    url(
        r'^place/$',
        views.PlaceListView.as_view(),
        name='place_browse'
    ),
    url(
        r'^place/detail/(?P<pk>[0-9]+)$',
        views.PlaceDetailView.as_view(),
        name='place_detail'
    ),
    url(
        r'^place/create/$',
        views.PlaceCreate.as_view(),
        name='place_create'
    ),
    url(
        r'^place/edit/(?P<pk>[0-9]+)$',
        views.PlaceUpdate.as_view(),
        name='place_edit'
    ),
    url(
        r'^place/delete/(?P<pk>[0-9]+)$',
        views.PlaceDelete.as_view(),
        name='place_delete'),
    url(
        r'^institution/$',
        views.InstitutionListView.as_view(),
        name='institution_browse'
    ),
    url(
        r'^institution/detail/(?P<pk>[0-9]+)$',
        views.InstitutionDetailView.as_view(),
        name='institution_detail'
    ),
    url(
        r'^institution/create/$',
        views.InstitutionCreate.as_view(),
        name='institution_create'
    ),
    url(
        r'^institution/edit/(?P<pk>[0-9]+)$',
        views.InstitutionUpdate.as_view(),
        name='institution_edit'
    ),
    url(
        r'^institution/delete/(?P<pk>[0-9]+)$',
        views.InstitutionDelete.as_view(),
        name='institution_delete'),
]
