# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('places', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='kind',
            field=models.ManyToManyField(blank=True, to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='institution',
            name='located_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='born_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_place', to='places.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='died_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_place', to='places.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='profession', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='title', to='vocabs.SkosConcept'),
        ),
    ]
