# Generated by Django 3.2.12 on 2022-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='institution',
            name='authority_url',
            field=models.CharField(blank=True, help_text='z.B.: https://d-nb.info/gnd/5184714-0', max_length=300, verbose_name='GND-ID'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('Partei', 'Partei'), ('Archiv', 'Archiv'), ('Kriegsfürsorgeorganisation', 'Kriegsfürsorgeorganisation'), ('Atelier', 'Atelier'), ('Verlag/Druckerei/Reproduktionsanstalt', 'Verlag/Druckerei/Reproduktionsanstalt'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', help_text='Partei, Archiv, sonstiges', max_length=300, verbose_name='Art der Institution'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Geburtsdatum, bitte im Format: YYYY-MM-DD', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Datum des Todes, bitte im Format: YYYY-MM-DD', null=True, verbose_name='Todesdatum'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geonames_id',
            field=models.CharField(blank=True, help_text='z.B.: https://d-nb.info/gnd/16075953-5', max_length=500, verbose_name='GND-ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('Stadt', 'Stadt'), ('Land', 'Land'), ('Gebiet/Region', 'Gebiet/Region')], max_length=50, null=True),
        ),
    ]
