# Generated by Django 3.2.12 on 2022-03-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20220328_1916'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cardcollection',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='card',
            name='archiv',
            field=models.ForeignKey(blank=True, help_text='Quelle, anhand derer die Texte von Bild- und Adressseite in die Datenbank eingetragen wurden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_docs_archived', to='entities.institution', verbose_name='Archiv/Quelle'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_collection',
            field=models.ForeignKey(blank=True, help_text='Zur besseren Zuordnung wurden die Karten einer chronologischen und formalen Serie zugeordnet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contain_cards', to='cards.cardcollection', verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='card',
            name='creator_inst',
            field=models.ManyToManyField(blank=True, help_text='An der Herstellung beteiligte Unternehmen', related_name='created_by_inst', to='entities.Institution', verbose_name='An der Herstellung beteiligte Unternehmen'),
        ),
        migrations.AlterField(
            model_name='card',
            name='creator_person',
            field=models.ManyToManyField(blank=True, help_text='Der Name des Künstlers bzw. Illustrators ist in der standardisierten Form Nachname, Vorname(n) angegeben. Dies umfasst lediglich den Künstler des Bildes, nicht jedoch Verfasser abgedruckter Gedichte oder Lieder.', related_name='created_by_person', to='entities.Person', verbose_name='Erzeuger des Bildes (Person)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='gelaufen',
            field=models.CharField(blank=True, help_text='Bezeichnet, ob die Karte postalisch versandt wurde (gel. für gelaufen) oder nicht (n. gel. für nicht gelaufen).', max_length=250, verbose_name='gelaufen'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img_back',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adressseite'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img_front',
            field=models.CharField(blank=True, max_length=250, verbose_name='Bildseite'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legacy_id',
            field=models.IntegerField(blank=True, help_text='Laufende Nummer. Alle identifizierten Karten, inklusive der Variationen, wurden mit fortlaufenden Nummern versehen. Auch für unidentifizierte Karten wurde eine laufende Nummer vergeben, und zwar einerseits für fehlende Nummern der Hauptserie und andererseits wenn ergänzende Quellen (Presseberichte, Verkaufslisten, Archivquellen etc.) einen bestimmten Kartentitel nennen, aufgrund derer diese Karten künftig identifiziert und zugeordnet werden könnten (vgl. z. B. die Thomas-Riss-Karten Nr. 959-967).', null=True, verbose_name='Lfd. Nr.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, help_text='Nummer innerhalb der Serie', max_length=25, verbose_name='Nr. innerhalb der Serie'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_back',
            field=models.TextField(blank=True, help_text='Alle Textelemente der Adressseite wurden hier buchstabengetreu eingetragen. Auf den Karten visuell getrennte Textelemente wurden durch ein Semikolon getrennt. Die Reihung beginnt immer mit der Widmung und erfolgt dann üblicherweise gegen den Uhrzeigersinn', verbose_name='Text Adressseite'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_front',
            field=models.TextField(blank=True, help_text='Alle Textelemente der Bildseite wurden hier buchstabengetreu eingetragen. Auf den Karten visuell getrennte Textelemente wurden durch ein Semikolon getrennt. Die Reihung beginnt immer mit der Widmung und erfolgt dann üblicherweise gegen den Uhrzeigersinn.', verbose_name='Text Bildseite (Zitat)'),
        ),
        migrations.AlterField(
            model_name='cardcollection',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=25, verbose_name='Serienkürzel'),
        ),
        migrations.AlterField(
            model_name='cardcollection',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name der Serie'),
        ),
        migrations.AlterField(
            model_name='cardcollection',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='Ist Teilserie von', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_parts', to='cards.cardcollection', verbose_name='Teilserie von'),
        ),
    ]
